import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import ProjectBanner from "../components/projects/projectBanner";
import ShowcaseSection from "../components/projects/showcaseSection";
import ProjectTechStack from "../components/projects/projectTechStack";
import InfoSectionPrimary from "../components/projects/infoSectionPrimary";
import InfoSectionSecondary from "../components/projects/infoSectionSecondary";

import Image from "next/image";
import st from "../../public/assets/images/stripes.svg";
import sq from "../../public/assets/images/square.svg";
import sc from "../../public/assets/images/scribble.svg";
import forest from "../../public/assets/images/forest.png";

export default function Project() {
  return (
    <div>
      <Head>
        <title>James Vovos - AI Game Asset Creator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-hintedwhite-50 px-10 relative overflow-hidden">
        {/* Change these to only be pages (refactor components to only be components later) */}
        <section className="min-h-screen">
          <Navbar />
          <div>
            <span className="square">
              <Image
                src={sq}
                alt="Square"
                className="square absolute overflow-hidden"
              />
            </span>
            <span className="stripes">
              <Image
                src={st}
                alt="Stripes"
                className="stripes absolute overflow-hidden"
              />
            </span>
            <ProjectBanner
              title="AI Game Asset Creator"
              desc="Procedurally generate game assets using artificial intelligence, custom pipelines and natural language processing (NLP). Create game assets from simple prompts such as a game description and theme. Utilises dreambooth research from Google and custom trained deep learning text-to-image generation models."
              video="https://youtu.be/JbxVSpukm7I"
            />
            <ProjectTechStack />
            <ShowcaseSection
              title="SAMPLE AI OUTPUT"
              desc="Here is a sample output our procedural pipeline created. This art was produced off of 2 simple inputs. One being a simple {theme} and the other being the {scene} of our game world. In this example 'skyrim' was the {theme} and 'set in the dark forests of Gloomhaven. The forest is looming with darkness and mystery with a river that glows blue at night for some reason. It evokes a sense of danger and foreboding, complimented by a misty atmosphere' was the {scene} in which our procedural model drew inspiration from."
              image={forest}
            />
            <span className="scribble">
              <Image
                src={sc}
                alt="Scribble"
                className="scribble absolute overflow-hidden"
              />
            </span>
            <InfoSectionSecondary
              title="CUSTOM PIPELINES"
              desc=""
              video="https://youtu.be/JbxVSpukm7I"
              thumbnail=""
            />
            <InfoSectionPrimary
              title="DIFFUSION MODELS"
              desc=""
              video="https://youtu.be/JbxVSpukm7I"
              thumbnail=""
            />
            <InfoSectionSecondary
              title="LLMS"
              desc=""
              video="https://youtu.be/JbxVSpukm7I"
              thumbnail=""
            />
          </div>
          <div>
            <Footer />
          </div>
        </section>
      </main>
    </div>
  );
}
