import Head from "next/head";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Hero from "./components/hero";
import ProjectCard from "./components/projectCard";
import ContactForm from "./components/contactForm";
import About from "./about";

export default function Home() {
  return (
    <div>
      <Head>
        <title>James Vovos Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-charcoal-50 px-10">
      <Navbar />
        <section className="min-h-screen">
          <Hero />
        </section>

        {/* Change these to only be pages (refactor components to only be components later) */}
        <section>
          <div>
            <About />
            <ProjectCard />
            <ContactForm />
          </div>
          <div>
            <Footer />
          </div>
        </section>
      </main>
    </div>
  );
}
