import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import deved from "../public/dev-ed-wave.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black px-10">
        <section className="min-h-screen">
          <Navbar />
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-customblue-50 font font-medium">
              James Vovos
            </h2>
            <h3 className="text-2xl py-2">Creative Software Engineer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Graduate Software Engineer studying Computer Science at Swinburne
              University.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-customblue-50 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image
              src={deved}
              layout="fill"
              objectFit="cover"
              alt="cartoon image"
            />
          </div>
          <p className={styles.description}>
            Check out my GitHub contributions{" "}
            <code className={styles.code}>github.com/jamesvovos</code>
          </p>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-80">
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum."
              <span className="text-customblue-50"> CLOCS-A</span> in
              collaboration with{" "}
              <span className="text-customblue-50"> SEPA </span>
            </p>
          </div>
          <div></div>
        </section>
      </main>
    </div>
  );
}
