import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import InfoSectionPrimary from "../components/projects/infoSectionPrimary";

export default function Project() {
  return (
    <div>
      <Head>
        <title>James Vovos Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-hintedwhite-50 px-10">
        {/* Change these to only be pages (refactor components to only be components later) */}
        <section className="min-h-screen">
          <Navbar />
          <div>
            <InfoSectionPrimary
              title="CLOCS-A"
              desc="Final Year Capstone project in collaboration with Transport NSW & CLOCS-A. Initiative to develop several-cutting edge mobile apps that help construction and logistics companies across Australia monitor and adhere to compliance standards in trucking logistics. Collaborated with a team of 4 incredible developers to build 3 fully integrated apps."
              video="https://youtu.be/ron3H1-aqj4"
              thumbnail=""
            />
          </div>
          <div>
            <Footer />
          </div>
        </section>
      </main>
    </div>
  );
}
