import Head from "next/head";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import ProjectBanner from "../components/projects/projectBanner";
import ShowcaseSection from "../components/projects/showcaseSection";
import ProjectTechStack from "../components/projects/projectTechStack";
import InfoSectionPrimary from "../components/projects/infoSectionPrimary";
import InfoSectionSecondary from "../components/projects/infoSectionSecondary";

import Image from "next/image";
import st from "../../public/assets/images/stripes.svg";
import sq from "../../public/assets/images/square.svg";
import sc from "../../public/assets/images/scribble.svg";

import figma from "../../public/assets/images/figma.png";
import fleet from "../../public/assets/images/fleet.png";
import driver from "../../public/assets/images/clocs.png";
import site from "../../public/assets/images/site.png";

export default function Project() {
  const techStack = ["react", "awsamplify", "graphql", "mapbox"];

  return (
    <div>
      <Head>
        <title>James Vovos - CLOCS-A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-hintedwhite-50 px-10 relative overflow-hidden">
        {/* Change these to only be pages (refactor components to only be components later) */}
        <section className="min-h-screen">
          <Navbar />
          <div>
            <span className="square">
              <Image
                src={sq}
                alt="Square"
                className="square absolute overflow-hidden"
              />
            </span>
            <span className="stripes">
              <Image
                src={st}
                alt="Stripes"
                className="stripes absolute overflow-hidden"
              />
            </span>
            <ProjectBanner
              title="CLOCS-A"
              desc="Final Year Capstone project in collaboration with Transport NSW &
          CLOCS-A. Initiative to develop several-cutting edge mobile apps that
          help construction and logistics companies across Australia monitor and
          adhere to compliance standards in trucking logistics. Collaborated
          with a team of 4 incredible developers to build 3 fully integrated
          apps."
              video="https://youtu.be/ron3H1-aqj4"
            />
            <ProjectTechStack techStack={techStack} />
            <ShowcaseSection
              title="FIGMA DESIGNS"
              desc="Designed multiple prototypes after discussions with key stakeholders and user testing. I designed the mobile device prototypes to match client specifications using Figma. This process involved using a collaborative approach with key stakeholders, and critical thinking to turn requirements into high quality code."
              image={figma}
            />
            <span className="scribble">
              <Image
                src={sc}
                alt="Scribble"
                className="scribble absolute overflow-hidden"
              />
            </span>
            <InfoSectionSecondary
              title="FLEET MANAGER APP"
              desc="React JS web application built for fleet managers to create custom driving routes for their drivers that ensured safety compliance. GPS tracking, geofencing and alerts were built in. The app also handled driver documentation and stored valid licenses and driver training documentation."
              image={fleet}
            />
            <InfoSectionPrimary
              title="DRIVER APP"
              desc="React Native mobile app built to handle both iOS and Android support. Allows drivers to safely navigate custom routes pre-approved and assigned by their fleet manager. Incorporates turn-by-turn navigation instructions via Mapbox SDK & API. Empowers drivers to log safety concerns as they arise, and complete their pre-start safety check on their vehicle all in one place before they start their journey."
              image={driver}
            />
            <InfoSectionSecondary
              title="SITE MANAGER APP"
              desc="React Native app built to allow site managers (those who allow trucks onto construction sites) to view their licenses, documentation, routes and notify relevant parties of any safety issues or compliance concerns as they arrive onto site."
              image={site}
            />
          </div>
          <div>
            <Footer />
          </div>
        </section>
      </main>
    </div>
  );
}
